image: gitpod/workspace-bun

tasks:
  - name: Init a bun project and run
    init: |
      if test ! -e package.json; then
        TMP_DIR=$(mktemp -d)
        shopt -s dotglob
        mv * $TMP_DIR/
        bun create --no-git next-app .
        cp -r $TMP_DIR/* ./
        rm -r $TMP_DIR
        shopt -u dotglob
      fi
      bun install
    command: |
      bun upgrade --canary
      bun dev

ports:
  - port: 3000
    onOpen: open-preview
